### ISSUE TITLE
SPLITS Parameter doesn't work

### ISSUE THREAD

**Issue by F3nr1s** [dustinkirkland/hollywood#12]
Hi,

I have tried hollywood (and think it is rather funny) but I found a bug:
The parameter for the SPLITS seems to be ignoriered (so it always takes exactly as many splits, as there are widgets)

I played a little bit with bin/hollywood and the problem seems to be in line 45
$tmux_launcher send-keys -t $PKG "$0"
Here the hollywood script is called again, without the SPLITS parameter, so it uses the count of the widgets.

So long,

**Comment by dustinkirkland** [comment]
Good catch!  I just committed the fix, and released a new version ;-)
