### ISSUE TITLE
Have changing display?

### ISSUE THREAD

**Issue by rrthomas** [dustinkirkland/hollywood#13]
The YouTube video https://www.youtube.com/watch?v=rVMn3xk5mcY shows a suitably-impressive changing display of panes. This doesn't happen when I run hollywood on my Ubuntu 16.04 machine. Did I miss something?

I looked at the code and it looks like the panels are built up and then left, so I wonder if this was removed or from an unreleased version or some other trick? Would be great to have it!

**Comment by dustinkirkland** [comment]
Good catch.  That code did disappear at some point.  I just added it back in today.  Thanks!

**Comment by rrthomas** [comment]
Most awesome, thanks!
