### ISSUE TITLE
Add settings and Music loop

### ISSUE THREAD

**Issue by edwinramirez** [dustinkirkland/hollywood#17]
Hi, I love this app but it would be great if you could have a settings file to set how many widgets are shown because it opens way too much on my screen and you can´t see anything since they are so small. 
Also it would be great if the music could be set to be on a loop.

Thanks and great job!

**Comment by dustinkirkland** [comment]
As of the most recent release, there is a new option [-s|--splits NUM] to specify the number of splits.  I'll look into the looping of the music.  Thanks!
