### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by ThirstyThursten** [dustinkirkland/hollywood#24]
I love your scripts/program!
Is there a way though to get the music out of it?
Or can I turn it off? 
Thanks in advance!

**Comment by ThirstyThursten** [comment]
Found the parameters in the script!

**Comment by meonkeys** [comment]
Note that muting is no longer an issue, the music was removed in f28b0ff9be60d4d076419275e483eaf078e96758.

See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944275

**Comment by dustinkirkland** [comment]
That's correct!  :-)
