### ISSUE TITLE
Known use in cinematic activities?

### ISSUE THREAD

**Issue by mightyiam** [dustinkirkland/hollywood#25]
I'm interested to know which cinematic activities this project has been used in, please.

**Comment by dustinkirkland** [comment]
So far:
 - NBC News: http://blog.dustinkirkland.com/2016/05/byobu-hollywood-melodrama-and-ubuntu.html
 - Saturday Night Live: http://blog.dustinkirkland.com/2016/10/a-parody-within-parody.html
 - Experian commercial: https://twitter.com/DustinKirkland/status/971423536936923136

I just added a screenshots/ directory to the source tree.

**Comment by mightyiam** [comment]
Thank you! Me and my friends were wondering!
