### ISSUE TITLE
Want to Mute the music

### ISSUE THREAD

**Issue by javiersorella-natgeo** [dustinkirkland/hollywood#27]
There is no option to mute the music!
I want to make a joke, not to transform my computer in a discoteque

**Comment by evil666** [comment]
Mute triggers are not working on arch version. -q, --quiet, --nosound all still kick off the music when entered. Since its from the aur its pulled from your git.

**Comment by PetrusKiendys** [comment]
Will this ever be fixed?

**Comment by dustinkirkland** [comment]
Fix committed.  Hollywood will now default to muted music, but you can re-enable it with "hollywood --sound".  Will be in the 1.15 release.
