### ISSUE TITLE
mi.mp4 File not found

### ISSUE THREAD

**Issue by T-vK** [dustinkirkland/hollywood#31]
OS: Ubuntu 18.04
hollywood version: 1.19 (the one that's currently in the master)

One of the widgets is just spamming the following error:
![image](https://user-images.githubusercontent.com/11368523/69883465-9dead100-12d4-11ea-8240-6690e513af43.png)

Any ideas what's wrong here?

**Comment by dustinkirkland** [comment]
Good catch, thanks.  I just uploaded a fix and released hollywood 1.20.  Thanks.

**Comment by T-vK** [comment]
Thanks for the quick fix! I no longer get the error now.
