### ISSUE TITLE
Ubuntu package version mplayer script without "-loop 0" option by default.

### ISSUE THREAD

**Issue by yangu-hury** [dustinkirkland/hollywood#35]
Package: hollywood
Version: 1.14-0ubuntu1

File path = /usr/lib/hollywood/mplayer

command -v mplayer >/dev/null 2>&1 || exit 1
trap "pkill -f -9 lib/hollywood/ >/dev/null 2>&1; exit" HUP INT QUIT TERM
PKG=hollywood
dir="$(dirname $0)/../../share/$PKG"
DISPLAY= mplayer -vo caca $MPLAYER_OPTS $dir/mi.mp4

Fix:

DISPLAY= mplayer -vo caca -loop 0 $MPLAYER_OPTS $dir/mi.mp4

**Comment by dustinkirkland** [comment]
This is fixed in newer versions of hollywood (1.16+).

Cheers,
@DustinKirkland
