### ISSUE TITLE
Hollywood snap fails to launch

### ISSUE THREAD

**Issue by kz6fittycent** [dustinkirkland/hollywood#39]
I've installed the snap and it's not launching. Tried running `snap run hollywood` rendered no output and I'm not seeing logs. This a lame issue/bug report I know but I got nothing. 

I'm happy to keep checking back as I find more logs/output. Just wanted you to be aware.

**Comment by darealshinji** [comment]
Same for me.

**Comment by fcole90** [comment]
+1

**Comment by stem2580** [comment]
> I've installed the snap and it's not launching. Tried running `snap run hollywood` rendered no output and I'm not seeing logs. This a lame issue/bug report I know but I got nothing.
> 
> I'm happy to keep checking back as I find more logs/output. Just wanted you to be aware.

what was the fix ?
