### ISSUE TITLE
Crash after quiting

### ISSUE THREAD

**Issue by Nairolf21** [dustinkirkland/hollywood#4]
Hi, 

It seems that hollywood is crashing after quiting terminal with Ctrl+C. Infact, after doing this, I have a report error, and music of Mission Impossible doesn't stop. 
I don't know how I can give you more information about this problem.

**Comment by dustinkirkland** [comment]
Okay, thanks. I'll see if I can reproduce it.

**Comment by Nairolf21** [comment]
In fact, I can give your more information. 
What I do : 
-Open terminal
-launch byobu
-launch hollywood

If stop hollywood with Ctrl+C, it's okay, I return on usual screen of byobu. But, if I quit it closing byobu with the 'close button', the music doesn't stop. I need to launch again byobu (in fact Hollywood entier seems continue), and stop it with Ctrl+C. 

I hope that this will you help better.

**Comment by dustinkirkland** [comment]
Okay, thanks for that.  So I've done two things...  First, I've set hollywood to run all widgets with a minimum scheduling priority via nice -n 19.  Secondly, I've added a note in the manpage.  These changes are released in hollywood 1.7.  Cheers!
