### ISSUE TITLE
Usage of hollywood in `Paint it Green - A SUSE Music Parody`

### ISSUE THREAD

**Issue by NotWearingPants** [dustinkirkland/hollywood#41]
I think hollywood is used in [Paint it Green - A SUSE Music Parody](https://www.youtube.com/watch?v=b0tsZB_LEQk), at 0:40, 0:53, 1:09, 1:33.

Thought I'd let you know, maybe add this to screenshots 🤷‍♂️

**Comment by dustinkirkland** [comment]
Awesome!  Thanks for the pointer.  I've added a link to it on the homepage
of hollywood.computer.  Cheers!

@DustinKirkland
