### ISSUE TITLE
soundwave.mp4 broken

### ISSUE THREAD

**Issue by vuongkienthanh** [dustinkirkland/hollywood#58]
I'm on linux mint 20.2 uma, `mpv` can open `soundwave.mp4` but only waves on video but no sound. Other mp4 on my pc are fine. 
I also tried it on the online player [www.hlsplayer.net](https://www.hlsplayer.net/mp4-player#type=mp4&src=https%3A%2F%2Fgithub.com%2Fdustinkirkland%2Fhollywood%2Fblob%2Fmaster%2Fshare%2Fhollywood%2Fsoundwave.mp4%3Fraw%3Dtrue), which gave the same result.

**Comment by dustinkirkland** [comment]
That's right. It's only a video.  The sound was deemed copyrighted.

**Comment by vuongkienthanh** [comment]
I installed through `apt install hollywood`, the program ran with no music. After browsing a while, i thought the bug was the mp4. Could you help me what to do next?
