### ISSUE TITLE
package as a snap

### ISSUE THREAD

**Issue by elopio** [dustinkirkland/hollywood#7]
This would be a really cool application to show as a snap.

I made an initial attempt, but I'm getting this error with devmode:
open terminal failed: not a terminal

devmode is supposed to let anything work, so I suppose there is bug in there, somewhere. I won't have time to keep playing with it today, so I'm leaving it here in case somebody else wants to give it a try. The file was renamed from .yaml to .txt to be able to upload it to github.
[snapcraft.txt](https://github.com/dustinkirkland/hollywood/files/266859/snapcraft.txt)

TODO:
- make it work in devmode.
- use less stage packages.
- talk to security about the "Bad system call" when installed without devmode.

**Comment by dustinkirkland** [comment]
I love the idea, but I assumed this would be a super complicated snap due to the long list of dependencies.  I'd love to see it work though!

**Comment by onlypentest** [comment]
trt

**Comment by dustinkirkland** [comment]
Oh, sorry, this is already available as a snap already!

https://uappexplorer.com/snap/ubuntu/hollywood
