### ISSUE TITLE
Please add support for screen backend (vs tmux)

### ISSUE THREAD

**Issue by p1r473** [dustinkirkland/hollywood#71]
Hello
I cant get this to work with screen backend, only tmux backend for Byobu [`byobu-select-backend`, `~/.byobu/backend`]
It works fine when I run on tmux backend but my usual backend screen gives the errors: no such file or directory when it tries to run `attach-session` and `send-keys`
Please support screen backend!

**Comment by dustinkirkland** [comment]
Hi there, I'm really sorry, but I very likely won't be adding support for the screen backend in Hollywood.  I've been slowly deprecating the screen backend in byobu for years, as it's become difficult-to-impossible to support many of the best tmux-like features, in screen.  My apologies!

**Comment by p1r473** [comment]
@dustinkirkland sure np, I understand! If you change your mind Id put a bounty on this

**Comment by dustinkirkland** [comment]
Heh :-)  Why is the screen backend more important to you?  Or, rather, why is the tmux backend not suitable?

**Comment by p1r473** [comment]
@dustinkirkland sorry for the delay-
the colors of Tmux backend are always wrong, no matter what I do I cant seem to get rid of that grey.
![image](https://github.com/dustinkirkland/hollywood/assets/9235633/b7f06199-99f4-449d-b240-21711527503e)
