### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AronasGITHUB** [dustinkirkland/hollywood#75]
Why did my terminal username's color change? It was usually green, white, and blue and then i got this mess of colors.
![Screenshot from 2024-10-05 08-52-06](https://github.com/user-attachments/assets/b0d9e8e1-490e-4845-bf00-8d271805d4ed)

**Comment by AronasGITHUB** [comment]
i fixed it myself, thanks

**Comment by switchmaxfx** [comment]
How did you fix this?

**Comment by voxain** [comment]
> i fixed it myself, thanks

theres a special seat in hell for you
